### ISSUE TITLE
keystore 签名算法问题导致的patch_unsigned.apk签名出问题

### ISSUE THREAD

**Issue by SHAU-LOK** [Tencent/tinker#118]
### 问题描述

> patch_unsigned.apk 文件内的内容是正常的，一到了patch_signed.apk，内容就全没有了

神奇发现我这边项目的keystore 签名算法是 ``SHA1withDSA``

源码的patchBuilder.java

```java
  private void signApk(File input, File output) throws IOException, InterruptedException {
        //sign apk
        if (config.mUseSignAPk) {
            Logger.d("Signing apk: %s", output.getName());
            if (output.exists()) {
                output.delete();
            }
            ArrayList<String> command = new ArrayList<>();
            command.add("jarsigner");
            command.add("-sigalg");
            command.add("MD5withRSA");
            command.add("-digestalg");
            command.add("SHA1");
            command.add("-keystore");
            command.add(config.mSignatureFile.getAbsolutePath());
            command.add("-storepass");
            command.add(config.mStorePass);
            command.add("-keypass");
            command.add(config.mKeyPass);
            command.add("-signedjar");
            command.add(output.getAbsolutePath());
            command.add(input.getAbsolutePath());
            command.add(config.mStoreAlias);

            Process process = new ProcessBuilder(command).start();
            process.waitFor();
            process.destroy();
            if (!output.exists()) {
                throw new IOException("Can't Generate signed APK. Please check if your sign info is correct.");
            }
        }
    }
```

### 解决方案

```
MD5withRSA -> SHA1withDSA
```

**Comment by shwenzhang** [comment]
android基本都是使用MD5withRSA的吧，我看看能不能直接通过旧的签名判断出来使用的方式

**Comment by shwenzhang** [comment]
sigalg algorithm: If this option is not specified, then SHA1withDSA, SHA256withRSA, or SHA256withECDSA are used depending on the type of private key.

will fix with 1.7.0

**Comment by shwenzhang** [comment]
@SHAU-LOK , please try with 1.7.0

**Comment by SHAU-LOK** [comment]
@shwenzhang Fixed,Thanks

**Comment by shixinglingguihua** [comment]
@shwenzhang  hello ，author 
  at version-1.8.1 ，
     exce java -jar tinker-patch-cli-1.8.1.jar -old old.apk -new new.apk -config tinker_config.xml -out output 
 but，I can not got the signed apk Patch， here  is log：

-----------------------Tinker patch begin-----------------------
configuration: 
oldApk:C:\Users\lingguihua\Desktop\lingguihua\workspace\tinker2\tinker-build\tinker-patch-cli\tool_output\old.apk
newApk:C:\Users\lingguihua\Desktop\lingguihua\workspace\tinker2\tinker-build\tinker-patch-cli\tool_output\new.apk
outputFolder:C:\Users\lingguihua\Desktop\lingguihua\workspace\tinker2\tinker-build\tinker-patch-cli\tool_output\tinkerPatch
isIgnoreWarning:false
isProtectedApp:false
7-ZipPath:7za
useSignAPk:true
package meta fields: 
filed name:patchMessage, filed value:classes.dex
filed name:platform, filed value:all
dex configs: 
dexMode: jar
dexPattern:classes.*\.dex
dexPattern:assets/secondary-dex-.\.jar
dex loader:com.smart.location.presentation.LocationApplication
dex loader:com.tencent.tinker.loader.*
dex loader:tinker.sample.android.SampleApplication
lib configs: 
libPattern:lib/.*/.*\.so
resource configs: 
resPattern:assets/.*
resPattern:resources\.arsc
resPattern:res/.*
resPattern:AndroidManifest\.xml
resIgnore change:assets/sample_meta\.txt
largeModSize:100kb
useApplyResource:false

Analyze old and new apk files:
old apk: old.apk, size=55014116, md5=2706fa754c11ee07d3540b5f7f1a276d
new apk: new.apk, size=55016657, md5=00a427e6a449f03325b723ce0a1cba99
UnZipping apk to C:\Users\lingguihua\Desktop\lingguihua\workspace\tinker2\tinker-build\tinker-patch-cli\tool_output\tinkerPatch\old
UnZipping apk to C:\Users\lingguihua\Desktop\lingguihua\workspace\tinker2\tinker-build\tinker-patch-cli\tool_output\tinkerPatch\new
Check for loader classes in dex: classes.dex
Check for loader classes in dex: classes2.dex
Check for loader classes in dex: classes3.dex
No dexes were changed, nothing needs to be done next.
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Signing key algorithm is SHA1withRSA



here is  java compiler throw  execption：

Signing key algorithm is SHA1withRSA
java.io.IOException: Cannot run program "jarsigner": CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(Unknown Source)
        at com.tencent.tinker.build.builder.PatchBuilder.signApk(PatchBuilder.java:141)
        at com.tencent.tinker.build.builder.PatchBuilder.buildPatch(PatchBuilder.java:62)
        at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:74)
        at com.tencent.tinker.patch.CliMain.run(CliMain.java:106)
        at com.tencent.tinker.patch.CliMain.main(CliMain.java:54)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 6 more

**Comment by shwenzhang** [comment]
java.io.IOException: Cannot run program "jarsigner": CreateProcess error=2, 系统找不到指定的文件。

**Comment by yuanxiaofan** [comment]
#823 @shwenzhang 这个问题相似但又不同，能帮我看看吗，谢谢大神！

**Comment by a8stefan** [comment]
大神解决没？
